[project]
authors = [
    {name = "Michael Vieira", email = "dev@mvieira.fr"},
]
maintainers = [
    { name = "Guillaume Gauvrit", email = "guillaume.gauvrit@gandi.net" },
]
license = {text = "BSD-3-Clause"}
requires-python = ">=3.11,<4"
dependencies = [
    "django >=4.1,<6.0",
    "sentry-sdk >=2.0,<3",
]
name = "dj-sentry"
version = "0.2.0"
description = "A Django app to initialize Sentry client for your Django applications"
readme = "README.md"
keywords = [
    "django",
    "sentry",
]

[project.urls]
repository = "https://github.com/Gandi/dj_sentry"

[dependency-groups]
dev = [
    "ruff>=0.15.18,<1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
